// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(69143302-D262-4BDA-BF73-FB09102B5052),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

